[package]
name = "poap_project"
version = "1.0.0"

[addresses]
risein_poap = "7348d11ab96e46f77338898a34b2da2fe64dea21dffb3b4060c9bcb5ac2e6c09"

[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects", rev = "mainnet" }
